name: GHAS Bootcamp Setup2
on: 
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  bootcamp-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      
      - name: Setup Orgs
        run: |
          # Set issue number as env variable
          WORKING_REPO=${{ github.event.repository.full_name }}
          ISSUE_NUM='40'

          # execute python script
          python bootcamp-setup.py $WORKING_REPO $ISSUE_NUM

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADMIN_TOKEN: ${{ secrets.ENT_ADMIN_TOKEN }}
